### ISSUE TITLE
:os_mon is required

### ISSUE THREAD

**Issue by gallypette** [phoenixframework/plds#8]
As `:os_mon` is registered in the extra_application, `plds` won't start if `erlang-os-mon` is not available on the system.
One can easily understand the issue when launching from master but it is a bit more tricky when using the escript:
```
➜  plds git:(main) ✗ mix phx.server                                                        
Generated plds app
[notice] Application runtime_tools exited: :stopped
** (Mix) Could not start application os_mon: could not find application file: os_mon.app
```
```
➜  plds git:(main) ✗ plds server --connect "toto@mynode" --cookie secret --open  
11:31:18.156 [notice] Application runtime_tools exited: :stopped
PLDS failed to start
```
After installing the package on ubuntu:
```
➜  plds git:(main) ✗ ./plds server --connect "toto@mynode" --cookie secret --open
11:38:08.350 [notice]     :alarm_handler: {:set, {:system_memory_high_watermark, []}}
[PLDS] using long names because one of the nodes is long. Current name is :"plds@127.0.0.1"
11:38:08.532 [info] [PLDS] Connected to node :"toto@mynode"
11:38:08.563 [info] Running PLDSWeb.Endpoint with cowboy 2.9.0 at :::8090 (http)
11:38:08.565 [info] Access PLDSWeb.Endpoint at http://localhost:8090
```

**Comment by josevalim** [comment]
Yes, you would have to install it. Anything we could have done to make it clearer?

**Comment by gallypette** [comment]
Hi Jose,
I think so, maybe in `https://hexdocs.pm/phoenix_live_dashboard/os_mon.html` because erlang doc is a bit dry in this regard. I installed `elixir` and `erlang` using `asdf` and it did not occur to me that `os_mon` had to be installed using the os package manager.

**Comment by josevalim** [comment]
Done in LiveDashboard :)

**Comment by gallypette** [comment]
You pushed into master, I am not sure it's intended ?
